### ISSUE TITLE
Albany undefined reference

### ISSUE THREAD

**Issue by ibaned** [SCOREC/core#206]
```
/.../test/TrilinosInstall/lib/libapf.a(apf.cc.o): In function `apf::getMatrixGrad(apf::Element*, apf::Vector3 const&, apf::Vector<27ul>&)':

apf.cc:(.text+0x591): undefined reference to `apf::MatrixElement::grad(apf::Vector3 const&, apf::Vector<27ul>&)'
```

**Comment by cwsmith** [comment]
@ibaned Is there any indication that this is resolved?

**Comment by ibaned** [comment]
I think I still see it in one build, but frankly the dashboard is in pieces for unrelated reasons.

**Comment by cwsmith** [comment]
OK.  Thanks for checking.   I assume waiting a few days to see if the build resolves is OK with you?

**Comment by ibaned** [comment]
Definitely

**Comment by JustinClough** [comment]
I'm working on this now on a machine at USC. I'm running into other build issues but the `apf::getMatrixGrad(...)` one hasn't shown up.

**Comment by JustinClough** [comment]
Just finished building Albany (with https://github.com/SNLComputation/Albany/commit/0b2836f6f8452ec93f113fde6a5d6de4a7728a1f)  and SCOREC/core (with https://github.com/SCOREC/core/commit/9e4b9fb76afbcf2e195b6ae2d135287a753adbfe) and did not see the `apf::getMatrixGrad(...)` error. I think Cameron's commit fixed the issue.

**Comment by ibaned** [comment]
But it hasn't made it into master... is something wrong with the automerge?

**Comment by JustinClough** [comment]
I'm closing this issue as https://github.com/SNLComputation/Albany/issues/421#issuecomment-453847927 was closed.
